[package]
name = "powerline-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
git2 = "0.19.0"
tokio = { version = "1.37.0", features = ["full"] }
unicode-segmentation = "1.11.0"
